# Generated by Django 5.0.3 on 2024-03-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre_alter_movie_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movies.genre', verbose_name='Жанр'),
        ),
    ]
